CREATE TABLE CRM_Data (
Lead_ID VARCHAR(10) PRIMARY KEY,
Lead_Name VARCHAR(100),
Company_Name VARCHAR(100),
Industry VARCHAR(50),
Country VARCHAR(50),
State VARCHAR(50),
City VARCHAR(50),
Lead_Source VARCHAR(50),
Lead_Status VARCHAR(50),
Contact_Name VARCHAR(100),
Email VARCHAR(100),
Phone_Number VARCHAR(20),
Account_Name VARCHAR(100),
Opportunity_Name VARCHAR(100),
Opportunity_Stage VARCHAR(50),
Expected_Revenue DECIMAL(12,2),
Probability INT,
Close_Date DATE,
Sales_Representative VARCHAR(100),
Account_Type VARCHAR(50),
Customer_Priority VARCHAR(20),
Customer_Satisfaction_Score DECIMAL(3,1),
Case_Status VARCHAR(30),
Last_Activity_Date DATE
);